version: "3.9"

services:
  nextapp:
    build: .
    container_name: next_intranet
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
    networks:
      - intranet_net

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - nextapp
    restart: always
    networks:
      - intranet_net

networks:
  intranet_net:
    driver: bridge
